server:
  port: 8201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.67.226:3306/springcloud
    username: xiaoli
    password: abC123456@

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.156.115:8848
  application:
    name: book